SELECT CODIGO, NOME FROM ALIMENTOS
SELECT * FROM ALIMENTOS


  #JOINS
SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTD
FROM ALIMENTOS A
INNER JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM ALIMENTOS A
JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTDE
FROM ALIMENTOS A
LEFT OUTER JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM COMPONENTES A
RIGHT OUTER JOIN ALIMENTOS B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTDE
FROM ALIMENTOS A
JOIN COMPONENTES B
ON (A.CODIGO  = B.CODALIMENTO)
WHERE A.CATEGORIA = 1

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM ALIMENTOS A JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)
WHERE A.CATEGORIA = 1 OR A.CATEGORIA = 2
ORDER BY A.CATEGORIA, A.DESCRICAO
