
#Select
  
SELECT CODIGO, NOME FROM ALIMENTOS
SELECT * FROM ALIMENTOS
SELECT * FROM FRUTAS;
SELECT * FROM VERDURAS;
SELECT * FROM CARNES;
SELECT * FROM PEIXES;
SELECT * FROM AÇÚCARES E DOCES;
SELECT * FROM ÓLEOS E GORDURAS;
SELECT * FROM GRÃOS E FARINÁCEOS;
SELECT * FROM LEITE E OVOS;
SELECT * FROM CEREAIS;

SELECT * FROM Alimentos
WHERE AlimentoID=1;

SELECT * FROM Alimentos
ORDER BY Preços;

SELECT * FROM Products
ORDER BY ProductName;

#JOINS
  
SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTD
FROM ALIMENTOS A
INNER JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM ALIMENTOS A
JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTDE
FROM ALIMENTOS A
LEFT OUTER JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM COMPONENTES A
RIGHT OUTER JOIN ALIMENTOS B
ON (A.CODIGO = B.CODALIMENTO)

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO, B.QTDE
FROM ALIMENTOS A
JOIN COMPONENTES B
ON (A.CODIGO  = B.CODALIMENTO)
WHERE A.CATEGORIA = 1

SELECT A.CODIGO, A.DESCRICAO, B.DESCRICAO
FROM ALIMENTOS A JOIN COMPONENTES B
ON (A.CODIGO = B.CODALIMENTO)
WHERE A.CATEGORIA = 1 OR A.CATEGORIA = 2
ORDER BY A.CATEGORIA, A.DESCRICAO
